/* Meeting */
export const GET_MEETING_DATA_REQUESTED = "GET_MEETING_DATA_REQUESTED";
export const GET_MEETING_DATA_SUCCESS = "GET_MEETING_DATA_SUCCESS";
export const GET_MEETING_DATA_FAILED = "GET_MEETING_DATA_FAILED";

/* User */
export const GET_USER_REQUESTED = "GET_USER_REQUESTED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";
